apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-to-tectonic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-to-tectonic
  template:
    metadata:
      labels:
        name: mongo-to-tectonic
    spec:
      containers:
        - image: bedrockio/mongo-to-tectonic
          imagePullPolicy: Always
          name: mongo-to-tectonic
          env:
            - name: NODE_ENV
              value: "production"
            - name: ENV_NAME
              value: "staging"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/tectonic_dev"
            - name: MONGO_COLLECTIONS_TO_INDEX_HISTORICAL
              value: ""
          ports:
            - name: http-server
              containerPort: 2455
          volumeMounts:
            - name: mongo-to-tectonic-cache
              mountPath: /service/data
      volumes:
        - name: mongo-to-tectonic-cache
          emptyDir: {}