version: "3.7"

services:
  api:
    command: [
        "./scripts/wait-for-it.sh",
        "mongo:27017",
        "--",
        "./scripts/wait-for-it.sh",
        "elasticsearch:9200",
        "--",
        "yarn",
        "start:production", # producion required to overwrite PUBSUB_EMULATOR_HOST
      ]
    environment:
      - MOCK_EMAIL=true
      - MONGO_URI=mongodb://mongo/tectonic_dev
      - PUBSUB_EMULATOR=false
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - GOOGLE_CLOUD_PROJECT=tectonic
    build:
      context: ./services/api
      dockerfile: Dockerfile
      args:
        ENV_NAME: development
    volumes:
      - ./services/api/src:/service/src
      - ./services/api/fixtures:/service/fixtures
      - ./services/api/scripts:/service/scripts
      - ./services/api/.env:/service/.env
      - ./services/api/openapi:/service/openapi
    ports:
      - 3300:3300
    links:
      - mongo
      - elasticsearch
    depends_on:
      - mongo
      - elasticsearch

  api-cli:
    command: bash -c "./scripts/wait-for-it.sh mongo:27017 && ./scripts/wait-for-it.sh elasticsearch:9200 && sleep 10 && node ./scripts/publish-fixture-events.js"
    environment:
      - MOCK_EMAIL=true
      - MONGO_URI=mongodb://mongo/tectonic_dev
      - PUBSUB_EMULATOR=false
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - GOOGLE_CLOUD_PROJECT=tectonic
      - API_URL=http://api:3300
    build:
      context: ./services/api
      dockerfile: Dockerfile.cli
      args:
        ENV_NAME: development
    volumes:
      - ./services/api/src:/service/src
      - ./services/api/fixtures:/service/fixtures
      - ./services/api/scripts:/service/scripts
      - ./services/api/.env:/service/.env
      - ./services/api/openapi:/service/openapi
    links:
      - api
      - mongo
      - elasticsearch
    depends_on:
      - api
      - mongo
      - elasticsearch

  web:
    command: ["yarn", "start"]
    build:
      context: ./services/web
      dockerfile: Dockerfile
      args:
        ENV_NAME: development
    volumes:
      - ./services/web/src:/service/src
    ports:
      - 3200:3200
    depends_on:
      - api

  mongo:
    image: mongo:5.0.2
    logging:
      driver: none
    ports:
      - 27017

  elasticsearch:
    image: elasticsearch:7.14.0
    ports:
      - 9200
      - 9300
    environment:
      - "discovery.type=single-node"
      - "logger.level=WARN"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports:
      - 5602:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    logging:
      driver: none
