version: "3.7"

services:
  api:
    command: ["./scripts/wait-for-it.sh", "mongo:27017", "--", "yarn", "start"]
    environment:
      - MONGO_URI=mongodb://mongo/tectonic_dev
    build:
      context: ./services/api
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./services/api/src:/service/src
      - ./services/api/emails:/service/emails
      - ./services/api/fixtures:/service/fixtures
      - ./services/api/scripts:/service/scripts
      - ./services/api/.env:/service/.env
      - ./services/api/openapi:/service/openapi
    ports:
      - "2300:2300"
    links:
      - mongo
    depends_on:
      - mongo

  web:
    command: ["yarn", "start"]
    build:
      context: ./services/web
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./services/web/src:/service/src
    ports:
      - "2200:2200"
      - "34001:34001"
    depends_on:
      - api

  mongo:
    image: mongo:4.4.4
    command: --serviceExecutor adaptive
    logging:
      driver: none
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"

  pubsub:
    build:
      context: ./services/pubsub-emulator
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
