version: "3.7"

services:
  api:
    command: [
        "./scripts/wait-for-it.sh",
        "mongo:27017",
        "--",
        "./scripts/wait-for-it.sh",
        "elasticsearch:9200",
        "--",
        "./scripts/wait-for-it.sh",
        "pubsub:9200",
        "--",
        "yarn",
        "start:production", # producion required to overwrite PUBSUB_EMULATOR_HOST
      ]
    environment:
      - MOCK_EMAIL=true
      - MONGO_URI=mongodb://mongo/tectonic_dev
      - PUBSUB_EMULATOR_HOST=pubsub:8200
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - GOOGLE_CLOUD_PROJECT=tectonic
    build:
      context: ./services/api
      dockerfile: Dockerfile
      args:
        ENV_NAME: development
    volumes:
      - ./services/api/src:/service/src
      - ./services/api/fixtures:/service/fixtures
      - ./services/api/scripts:/service/scripts
      - ./services/api/.env:/service/.env
      - ./services/api/openapi:/service/openapi
    ports:
      - "3300:3300"
    links:
      - mongo
      - pubsub
      - elasticsearch
      - api-elasticsearch-worker
    depends_on:
      - mongo
      - pubsub
      - elasticsearch
      - api-elasticsearch-worker

  api-elasticsearch-worker:
    command: [
        "./scripts/wait-for-it.sh",
        "mongo:27017",
        "--",
        "./scripts/wait-for-it.sh",
        "elasticsearch:9200",
        "--",
        "./scripts/wait-for-it.sh",
        "pubsub:9200",
        "--",
        "yarn",
        "elasticsearch-sink:start:production", # producion required to overwrite PUBSUB_EMULATOR_HOST
      ]
    environment:
      - MOCK_EMAIL=true
      - MONGO_URI=mongodb://mongo/tectonic_dev
      - PUBSUB_EMULATOR_HOST=pubsub:8200
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - GOOGLE_CLOUD_PROJECT=tectonic
    build:
      context: ./services/api
      dockerfile: Dockerfile.elasticsearch-sink
      args:
        ENV_NAME: development
    volumes:
      - ./services/api/src:/service/src
      - ./services/api/fixtures:/service/fixtures
      - ./services/api/scripts:/service/scripts
      - ./services/api/.env:/service/.env
      - ./services/api/openapi:/service/openapi
    links:
      - mongo
      - pubsub
      - elasticsearch
    depends_on:
      - mongo
      - pubsub
      - elasticsearch

  web:
    command: ["yarn", "start"]
    build:
      context: ./services/web
      dockerfile: Dockerfile
      args:
        ENV_NAME: development
    volumes:
      - ./services/web/src:/service/src
    ports:
      - "3200:3200"
    depends_on:
      - api

  mongo:
    image: mongo:4.4.4
    command: --serviceExecutor adaptive
    logging:
      driver: none
    ports:
      - 27017

  pubsub:
    build:
      context: ./services/pubsub-emulator
      dockerfile: Dockerfile
    ports:
      - 8200

  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch
    ports:
      - 9200
      - 9300
    environment:
      - "discovery.type=single-node"
