FROM node:14.16-alpine

ARG NODE_ENV=production

# Install app dependencies
COPY package.json /service/package.json
COPY yarn.lock /service/yarn.lock

# Update & install required packages
RUN apk add --update bash curl;
RUN cd /service; yarn install --frozen-lockfile;

# Copy app source
COPY . /service

# Set work directory to /api
WORKDIR /service

# start command as per package.json
CMD ["./scripts/cli-entrypoint.sh"]
