apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cli-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cli
  template:
    metadata:
      labels:
        app: api-cli
    spec:
      containers:
        - image: gcr.io/bedrock-foundation/tectonic-services-api-cli
          imagePullPolicy: Always
          name: api-cli
          env:
            - name: ENV_NAME
              value: staging
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              value: "mongodb://mongo:27017/tectonic_staging"
            - name: ELASTICSEARCH_URI
              value: "http://elasticsearch:9200"
            - name: ADMIN_EMAIL
              value: admin@tectonic.io
            - name: ADMIN_PASSWORD
              value: Bedrock.lake!
            - name: API_URL
              value: "https://tectonic-api.bedrock.foundation"
            - name: BATCHES_STORE
              value: gcs
            - name: BATCHES_GCS_BUCKET
              value: bedrock-foundation-tectonic-batches
          volumeMounts:
            - name: jobs-cache
              mountPath: /workdir/data
      volumes:
        - name: jobs-cache
          emptyDir: {}
