apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-jobs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-jobs
  template:
    metadata:
      labels:
        app: api-jobs
    spec:
      containers:
        - image: gcr.io/bedrock-foundation/tectonic-services-api-jobs
          imagePullPolicy: Always
          name: main
          env:
            - name: ENV_NAME
              value: staging
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              value: "mongodb://mongo:27017/tectonic_staging"
            - name: ELASTICSEARCH_URI
              value: "http://elasticsearch:9200"
            - name: APP_DOMAIN
              value: tectonic.io
            - name: POSTMARK_FROM
              value: no-reply@tectonic.io
            - name: POSTMARK_APIKEY
              value: abc
          volumeMounts:
            - name: cache
              mountPath: /service/data
      volumes:
        - name: cache
          emptyDir: {}
