apiVersion: v1
kind: Service
metadata:
  name: tectonic-web
  labels:
    name: tectonic-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 2200
      protocol: TCP
  selector:
    app: web
  loadBalancerIP: 35.227.92.99
