apiVersion: v1
kind: Service
metadata:
  name: tectonic-api
  labels:
    name: tectonic-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 2300
      protocol: TCP
  selector:
    app: api
  loadBalancerIP: 35.231.101.6
