apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: bedrockio/tectonic-web
          imagePullPolicy: Always
          name: main
          env:
            - name: ENV_NAME
              value: staging
            - name: NODE_ENV
              value: production
            - name: DOMAIN
              value: "bedrock.foundation"
            - name: API_URL
              value: "https://tectonic-api.bedrock.foundation"
          ports:
            - name: http-server
              containerPort: 3200
