#!/usr/bin/env node

const process = require('process');
const { logger } = require('@bedrockio/instrumentation');
const { initialize } = require('./../src/lib/pubsub');

async function run() {
  await initialize();
  logger.info('Initialize pubsub topics and subscriptions');
}

run()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    logger.error(`Fatal error: ${error.message}, exiting.`);
    console.warn(error.stack);
    process.exit(1);
  });
